---
# Copyright 2020 KubeInit.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.


#
# Make sure the mount path of libvirt has enough space in the hypervisor
#

- name: Get libvirt directory free space
  shell: |
    set -o pipefail
    df -BG --output=avail {{ kubeinit_validations_libvirt_path }} | grep -v Avail
  register: libvirt_free_space
  changed_when: "libvirt_free_space.rc == 0"
  tags:
    - provision_libvirt

- name: Get total inventory disk usage
  set_fact:
    kubeinit_validations_libvirt_disk_usage: "{{ kubeinit_validations_libvirt_disk_usage|int + hostvars[item].disk[:-1]|int }}"
  with_items:
    - "{{ groups['okd_service_nodes'] }}"
    - "{{ groups['okd_bootstrap_nodes'] }}"
    - "{{ groups['okd_master_nodes'] }}"
    - "{{ groups['okd_worker_nodes'] }}"
  tags:
    - provision_libvirt

- name: Make sure there is enough free space
  assert:
    that:
      - libvirt_free_space.stdout[:-1]|int > kubeinit_validations_libvirt_disk_usage|float * 1.1
    msg: The sum of the disk images must be higher than the available space + 10%
  tags:
    - provision_libvirt
