---
- name: Installer configuration tasks
  block:
          - include_tasks: 10_configure_install_config.yml
          - include_tasks: 20_create_manifests.yml
          - include_tasks: 30_create_ignition.yml
          - include_tasks: 40_prepare_ignition.yml
          - include_tasks: 50_prepare_isos.yml
  tags: installer_configuration
