---
# Copyright 2020 KubeInit.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.


#
# Set facts
#

- name: define host, node and ovn related facts
  ansible.builtin.set_fact:
    kubeinit_libvirt_ovn_enabled: "{{ True if (groups['all_hosts'] | length > 1) else kubeinit_common_ovn_enabled_default }}"
    kubeinit_bastion_host: "{{ groups['all_hosts'][0] }}"
    kubeinit_bastion_host_address: "{{ hostvars[groups['all_hosts'][0]]['ansible_default_ipv4']['address'] }}"
    kubeinit_apache_service_address: "{{ hostvars[groups['all_service_nodes'][0]].ansible_host }}"
    kubeinit_bind_service_address: "{{ hostvars[groups['all_service_nodes'][0]].ansible_host }}"
    kubeinit_haproxy_service_address: "{{ hostvars[groups['all_service_nodes'][0]].ansible_host }}"
    kubeinit_nexus_service_address: "{{ hostvars[groups['all_service_nodes'][0]].ansible_host }}"
    kubeinit_nexus_service_hostname: "{{ hostvars[groups['all_service_nodes'][0]].inventory_hostname }}"
    kubeinit_nfs_service_address: "{{ hostvars[groups['all_service_nodes'][0]].ansible_host }}"
    kubeinit_registry_service_hostname: "{{ hostvars[groups['all_service_nodes'][0]].inventory_hostname }}"
    kubeinit_services_service_address: "{{ hostvars[groups['all_service_nodes'][0]].ansible_host }}"
    kubeinit_services_service_hostname: "{{ hostvars[groups['all_service_nodes'][0]].inventory_hostname }}"
    kubeinit_services_pod_name: "kubeinit-service-pod"
    kubeinit_service_user: "root"
    kubeinit_service_user_dir: "/root"
    kubeinit_ingress_hostname: "ingress"
  with_items:
    - "{{ groups['all_hosts'] }}"
    - localhost
  delegate_to: "{{ item }}"

- name: Experimental warning
  ansible.builtin.debug:
    msg:
      - '|-------------------------------------------------------|'
      - '| Deploying in multiple hosts is experimental, parts of |'
      - '| the deployment might be broken or some distributions  |'
      - '| might not work as expected.                           |'
      - '|-------------------------------------------------------|'
  when: kubeinit_libvirt_ovn_enabled

#
# Cleanup hosts now before validations are run
#

- name: Cleanup the hosts before validations
  ansible.builtin.include_role:
    name: "../../roles/kubeinit_libvirt"
    tasks_from: 10_cleanup.yml
  with_items:
    - "{{ groups['all_hosts'] | list }}"
  loop_control:
    loop_var: cluster_role_item
  vars:
    kubeinit_deployment_node_name: "{{ cluster_role_item }}"
