---
# Copyright kubeinit contributors
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

#
# Prepare hypervisors by first gathering facts
#
- name: Add an explicit localhost entry to hostvars
  ansible.builtin.add_host:
    name: localhost
    ansible_connection: local
    ansible_python_interpreter: "{{ ansible_playbook_python }}"

- name: Gather localhost and hypervisor facts
  ansible.builtin.include_tasks: gather_host_facts.yml
  loop: "{{ groups['hypervisor_hosts'] | union(['localhost']) }}"
  loop_control:
    loop_var: cluster_role_item
  vars:
    kubeinit_deployment_node_name: "{{ cluster_role_item }}"

- name: Create a pseudo-host to hold the facts for the cluster as a whole
  ansible.builtin.add_host:
    name: 'kubeinit-facts'
    tasks_completed: "{{ ['task-gather-hypervisor-facts'] }}"

- block:
    - name: Check to see if we should stop here
      ansible.builtin.debug: msg="Stopping after '{{ kubeinit_stop_after_task }}'"
    - name: End play
      ansible.builtin.meta: end_play
  when: kubeinit_stop_after_task is defined and kubeinit_stop_after_task in hostvars['kubeinit-facts'].tasks_completed
