---
run-kubeinit-jobs:
  image: fedora
  tags:
    - kubeinit-ci-bot
  script:
    - python3 ./ci/launch_e2e.py
  only:
    variables:
      - $SCOPE == "kubeinit"

run-submariner-jobs:
  image: fedora
  tags:
    - kubeinit-ci-bot
  script:
    - python3 ./ci/launch_submariner_operator.py
  only:
    variables:
      - $SCOPE == "submariner"
