image: fedora
job:on-schedule:
  # only:
  #   - schedules
  tags:
    - kubeinit-ci-bot
  script:
    - sudo dnf install python3-pip -y
    - sudo yum group install "Development Tools" -y
    - sudo pip3 install PyGithub
    - python3 ./ci/launch_e2e.py
