---
run-periodic-jobs:
  image: fedora
  tags:
    - kubeinit-ci-bot
  script:
    - python3 ./ci/launch_e2e_periodic.py "$DISTROS"
  only:
    variables:
      - $SCOPE == "periodic"

run-kubeinit-jobs:
  image: fedora
  tags:
    - kubeinit-ci-bot
  script:
    - python3 ./ci/launch_e2e_kubeinit.py
  only:
    variables:
      - $SCOPE == "kubeinit"

run-submariner-jobs:
  image: fedora
  tags:
    - kubeinit-ci-bot
  script:
    - python3 ./ci/launch_e2e_submariner.py
  only:
    variables:
      - $SCOPE == "submariner"
