---
# The scope can be:
# PERIODIC: a periodic job running in kubeinit.
# PR: a PR job running in kubeinit.
# SUBMARINER: a PR job running in the submariner operator repository.

run-singlenode:
  image: fedora
  tags:
    - kubeinit-ci-singlenode
  script:
    - python3 ./ci/launch_e2e.py singlenode "$JOB_TYPE"
  only:
    variables:
      - $CLUSTER_TYPE == "singlenode"

run-multinode:
  image: fedora
  tags:
    - kubeinit-ci-multinode
  script:
    - python3 ./ci/launch_e2e.py multinode "$JOB_TYPE"
  only:
    variables:
      - $CLUSTER_TYPE == "multinode"
