---
# Docker hub login variables
kubeinit_common_docker_username: "{{ lookup('env','KUBEINIT_COMMON_DOCKER_USERNAME') | default ('') }}"
kubeinit_common_docker_password: "{{ lookup('env','KUBEINIT_COMMON_DOCKER_PASSWORD') | default ('') }}"

kubeinit_common_certificate_country: "{{ lookup('env','KUBEINIT_COMMON_CERTIFICATE_COUNTRY') or 'US' }}"
kubeinit_common_certificate_state: "{{ lookup('env','KUBEINIT_COMMON_CERTIFICATE_STATE') or 'MyState' }}"
kubeinit_common_certificate_locality: "{{ lookup('env','KUBEINIT_COMMON_CERTIFICATE_LOCALITY') or 'MyCity' }}"
kubeinit_common_certificate_organization: "{{ lookup('env','KUBEINIT_COMMON_CERTIFICATE_ORGANIZATION') or 'MyCompany' }}"
kubeinit_common_certificate_organizational_unit: "{{ lookup('env','KUBEINIT_COMMON_CERTIFICATE_ORGANIZATIONAL_UNIT') or 'MyDepartment' }}"

kubeinit_common_dns_master: "{{ lookup('env','KUBEINIT_COMMON_DNS_MASTER') or '1.1.1.1' }}"
kubeinit_common_external_access_enabled: "{{ (lookup('env','KUBEINIT_COMMON_EXTERNAL_ACCESS_ENABLED') | bool) or false }}"
kubeinit_common_ovn_enabled_default: "{{ (lookup('env','KUBEINIT_COMMON_OVN_ENABLED_DEFAULT') | bool) or false }}"
