---
# Docker hub login variables
kubeinit_common_docker_username: "{{ lookup('env','KUBEINIT_COMMON_DOCKER_USERNAME') | default ('') }}"
kubeinit_common_docker_password: "{{ lookup('env','KUBEINIT_COMMON_DOCKER_PASSWORD') | default ('') }}"

# Openshift deployment type and token info
kubeinit_common_openshift_deploy: "{{ (lookup('env','KUBEINIT_COMMON_OPENSHIFT_DEPLOY') | bool) or false }}"
kubeinit_common_openshift_pullsecret: "{{ lookup('env','KUBEINIT_COMMON_OPENSHIFT_PULLSECRET') | default ('') }}"

kubeinit_common_certificate_country: "{{ lookup('env','KUBEINIT_COMMON_CERTIFICATE_COUNTRY') or 'US' }}"
kubeinit_common_certificate_state: "{{ lookup('env','KUBEINIT_COMMON_CERTIFICATE_STATE') or 'MyState' }}"
kubeinit_common_certificate_locality: "{{ lookup('env','KUBEINIT_COMMON_CERTIFICATE_LOCALITY') or 'MyCity' }}"
kubeinit_common_certificate_organization: "{{ lookup('env','KUBEINIT_COMMON_CERTIFICATE_ORGANIZATION') or 'MyCompany' }}"
kubeinit_common_certificate_organizational_unit: "{{ lookup('env','KUBEINIT_COMMON_CERTIFICATE_ORGANIZATIONAL_UNIT') or 'MyDepartment' }}"

kubeinit_common_dns_public: "{{ lookup('env','KUBEINIT_COMMON_DNS_PUBLIC') or '1.1.1.1' }}"
