---

# Ansible vars
ansible_python_interpreter: '/usr/bin/python3'
ansible_ssh_pipelining: True
ansible_ssh_common_args: '-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=accept-new'

ansible_debug_enabled: "{{ (lookup('env','ANSIBLE_DEBUG') | bool) or false }}"
