---

#
# Additional defaults that can be provided with environment vars
#

###
# This variable configures the Docker hub login when running the deployment.
# The variable is defaulted to the content of the environment variable
# KUBEINIT_COMMON_DOCKER_USERNAME, both docker_username and docker_password must
# be used together.
docker_username: "{{ lookup('env','KUBEINIT_COMMON_DOCKER_USERNAME') | default(omit) }}"
###
# This variable configures the Docker hub password when running the deployment.
# The variable is defaulted to the content of the environment variable
# KUBEINIT_COMMON_DOCKER_PASSWORD, both docker_username and docker_password must
# be used together.
docker_password: "{{ lookup('env','KUBEINIT_COMMON_DOCKER_PASSWORD') | default(omit) }}"

###
# This variable configure if Openshift will be deployed.
openshift_deploy: "{{ (lookup('env','KUBEINIT_COMMON_OPENSHIFT_DEPLOY') | bool) or false }}"
###
# OpenShift pullsecret.
openshift_pullsecret: "{{ lookup('env','KUBEINIT_COMMON_OPENSHIFT_PULLSECRET') | default(omit) }}"

###
# Certificate default country.
certificate_country: "{{ lookup('env','KUBEINIT_COMMON_CERTIFICATE_COUNTRY') or 'US' }}"
###
# Certificate default state.
certificate_state: "{{ lookup('env','KUBEINIT_COMMON_CERTIFICATE_STATE') or 'MyState' }}"
###
# Certificate default locality.
certificate_locality: "{{ lookup('env','KUBEINIT_COMMON_CERTIFICATE_LOCALITY') or 'MyCity' }}"
###
# Certificate default organization.
certificate_organization: "{{ lookup('env','KUBEINIT_COMMON_CERTIFICATE_ORGANIZATION') or 'MyCompany' }}"
###
# Certificate default OU.
certificate_organizational_unit: "{{ lookup('env','KUBEINIT_COMMON_CERTIFICATE_ORGANIZATIONAL_UNIT') or 'MyDepartment' }}"

###
# Default public DNS.
dns_public: "{{ lookup('env','KUBEINIT_COMMON_DNS_PUBLIC') or '1.1.1.1' }}"

###
# Default SSH key type.
ssh_keytype: "{{ lookup('env','KUBEINIT_COMMON_SSH_KEYTYPE') or 'rsa' }}"
