---

###
# The default for the cluster network name is kimgtnet0.
#
# You can override this by setting a specific value for network_name in the
# kubeinit_network_spec command line variable, e.g.
# -e kubeinit_network_spec='[network_name=mynetwork]'
#
# The network name will be used to create a libvirt network for the cluster
# guest vms. The network cidr will set the range of addresses reserved for
# the cluster nodes. The gateway offset will be used to select the gateway
# address within the range, a negative offset starts at the end of the range,
# so for network=10.0.0.0/24, gateway_offset=-2 will select 10.0.0.254 and
# gateway_offset=1 will select 10.0.0.1 as the address. The other offset
# attributes follow the same convention.

network: 10.0.0.0/24
gateway_offset: -2
nameserver_offset: -3
dhcp_start_offset: 1
dhcp_end_offset: -4
