---
# Copyright 2019 Pystol (pystol.org).
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.


# "pystol" will search for and load any operating system variable file

# found within the "vars/" path. If no OS files are found the task will skip.
- name: Gather variables for each operating system
  include_vars: "{{ item }}"
  with_first_found:
    - skip: true
      files:
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ansible_distribution | lower }}.yml"
        - "{{ ansible_os_family | lower }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
        - "{{ ansible_os_family | lower }}.yml"
  tags:
    - always

- name: Include os family vars
  include_vars: "vars/{{ ansible_os_family }}.yml"

- name: install requirements
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - git
  tags:
    - pystol_install

- name: Clone pystol repo
  git:
    repo: 'https://github.com/pystol/pystol.git'
    dest: /root/pystol
    version: master
  tags:
    - pystol_install

- name: deploy pystol
  shell: |
    set -o pipefail
    # We apply the RBAC rules
    kubectl apply -f helm/templates/rbac.yaml
    echo
    # We deploy the operator using the image we created in the previous steps.
    # helm template is used to render the template with the needed parameters
    # ./helm/: Is the folder in which the Charts.yaml is defined
    # -f: Is the values.yaml with the default values deploying from stable:master
    # -x: Is the particular file we want to render
    helm template \
      --set appSettings.pystol.ui.image=quay.io/pystol/pystol-operator-stable:latest \
      --set appSettings.pystol.controller.image=quay.io/pystol/pystol-operator-stable:latest \
      --set appSettings.pystol.ui.api_host='10.0.0.1' \
      --set appSettings.pystol.ui.api_port=3000 \
      ./helm/ \
      -f helm/templates/values.yaml \
      -x templates/operator.yaml \
      | kubectl apply -f -
    echo
    # We add the CRD
    kubectl apply -f helm/templates/crd.yaml
    echo
  args:
    chdir: /root/pystol
  changed_when: false
  tags:
    - pystol_install
