---
namespace: kubeinit
name: kubeinit
version: 0.1.0
readme: README.md
authors:
  - Carlos Camacho <carloscamachoucv@gmail.com>
  # Keep this at the bottom
  - kubeinit (https://github.com/kubeinit)
description: KubeInit
license:
  - Apache-2.0
tags:
  - kubernetes
  - okd
  - openshift
dependencies: {}
repository: 'https://github.com/kubeinit/kubeinit'
homepage: 'https://github.com/kubeinit/kubeinit'
issues: 'https://github.com/kubeinit/kubeinit/issues'
