---
namespace: kubeinit
name: kubeinit
version: 1.0.2
readme: README.md
authors:
  - Carlos Camacho <carloscamachoucv@gmail.com>
  # Keep this at the bottom
  - kubeinit (https://github.com/kubeinit)
description: KubeInit
license:
  - Apache-2.0
tags:
  - k8s
  - okd
  - rke
  - cdk
  - eks
  - kubernetes
  - openshift
  - origin
  - canonical
  - rancher
  - aws
dependencies:
  ansible.posix: '>=1.1.1'
  community.crypto: '>=1.4.0'
  community.general: '>=1.3.5,<2.0.0'
  community.libvirt: '>=1.0.0'
  containers.podman: '>=1.4.1'
repository: 'https://github.com/kubeinit/kubeinit'
homepage: 'https://www.kubeinit.com'
issues: 'https://github.com/kubeinit/kubeinit/issues'
