#
# Kubeinit Ansible requirements
#

---
collections:
  - name: ansible.posix
    version: '1.1.1'
  - name: community.crypto
    version: '1.4.0'
  - name: community.general
    version: '1.3.5'
  - name: community.libvirt
    version: '1.0.0'
  - name: containers.podman
    version: '1.5.0'
