#
# Kubeinit Ansible requirements
#

---
collections:
  - ansible.posix
  - community.crypto
  - community.general
  - community.libvirt
  - containers.podman
#  - name: https://github.com/containers/ansible-podman-collections
#    type: git
#    version: 1.3.2
#    trackbranch: master
