---
# Copyright kubeinit.com
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.


- name: Check kubeinit_external_service_target
  block:

    - name: "check if the external bridge is created when using the external interface"
      ansible.builtin.shell: |
        set -o pipefail
        nmcli con show | grep {{ kubeinit_inventory_network_bridge_external }}
      register: bridge_status
      ignore_errors: yes

    - name: Create the detach interface script
      ansible.builtin.template:
        src: "../../roles/kubeinit_libvirt/templates/detach.sh.j2"
        dest: "~/detach.sh"
        mode: "0755"
      when: >
        bridge_status.rc != 0

    #
    # The next two tasks are dangerous so for now we leave them commented for now
    #

    # - name: Detach the physical network interface and attach it to the external bridge (OVN)
    #   ansible.builtin.command: ~/detach.sh YesImReallySure OVN
    #   async: 45
    #   poll: 0
    #   when: >
    #     kubeinit_libvirt_ovn_enabled and
    #     bridge_status.rc != 0

    # - name: Detach the physical network interface and attach it to the external bridge (Linux bridge)
    #   ansible.builtin.command: ~/detach.sh YesImReallySure
    #   async: 45
    #   poll: 0
    #   when: >
    #     not kubeinit_libvirt_ovn_enabled and
    #     bridge_status.rc != 0

    - name: Message before fail (external bridge not found)
      ansible.builtin.debug:
        msg:
          - "The bridge {{ kubeinit_inventory_network_bridge_external }} to provide external connectivity is not created."
          - "This is a requirement that needs to be addressed before running the playbook."
          - "You must create {{ kubeinit_inventory_network_bridge_external }} in {{ kubeinit_external_service_target }} before continue."
          - "It is created a script called ~/detach.sh in the hypervisor where the"
          - "service node will be deployed. This script will help to detach the physical"
          - "interface without breaking the network connectivity of the host."
          - ""
          - "**********************************************************************"
          - "* WARNING: Make sure that if you use OVN (multiple hypervisors), you *"
          - "* create an OVS bridge, and if you use libvirt (single hypervisor)   *"
          - "* then use a Linux bridge.                                           *"
          - "* Refer to: http://docs.kubeinit.com/usage.html#external-interface   *"
          - "* for further details.                                               *"
          - "**********************************************************************"
      when: |
        bridge_status.rc != 0

    - name: Fail if the external bridge is not created when using the external interface
      ansible.builtin.fail:
        msg: "Bridge {{ kubeinit_inventory_network_bridge_external }} required in {{ kubeinit_external_service_target }} but not found"
      when: |
        bridge_status.rc != 0

  delegate_to: "{{ kubeinit_external_service_target }}"
