---
# Copyright kubeinit.com
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

- name: "verify that {{ kubeinit_deployment_role }} nodes are ok"
  ansible.builtin.shell: |
    set -o pipefail
    export KUBECONFIG=~/install_dir/auth/kubeconfig; \
    oc get nodes | grep {{ kubeinit_deployment_role }} | grep " Ready"
  args:
    executable: /bin/bash
  register: cmd_res_nodes_ok
  changed_when: "cmd_res_nodes_ok.rc == 0"
  retries: 60
  delay: 60
  until: cmd_res_nodes_ok.stdout_lines | default([]) | list | count == groups['all_control_plane_nodes'] | count
  delegate_to: "{{ hostvars[kubeinit_deployment_node_name].ansible_host }}"

- name: "use single node cluster"
  ansible.builtin.shell: |
    set -o pipefail
    export KUBECONFIG=~/install_dir/auth/kubeconfig
    oc get nodes

    oc patch clusterversion/version --type='merge' -p "$(cat <<- EOF
    spec:
      overrides:
        - group: apps/v1
          kind: Deployment
          name: etcd-quorum-guard
          namespace: openshift-machine-config-operator
          unmanaged: true
    EOF
    )"
    oc scale --replicas=1 deployment/etcd-quorum-guard -n openshift-machine-config-operator || true
    oc scale --replicas=1 ingresscontroller/default -n openshift-ingress-operator || true
    oc scale --replicas=1 deployment.apps/console -n openshift-console || true
    oc scale --replicas=1 deployment.apps/downloads -n openshift-console || true
    oc scale --replicas=1 deployment.apps/oauth-openshift -n openshift-authentication || true
    oc scale --replicas=1 deployment.apps/packageserver -n openshift-operator-lifecycle-manager || true
    # Optional
    oc scale --replicas=1 deployment.apps/prometheus-adapter -n openshift-monitoring || true
    oc scale --replicas=1 deployment.apps/thanos-querier -n openshift-monitoring || true
    oc scale --replicas=1 statefulset.apps/prometheus-k8s -n openshift-monitoring || true
    oc scale --replicas=1 statefulset.apps/alertmanager-main -n openshift-monitoring || true

    oc patch etcd cluster -p='{"spec": {"unsupportedConfigOverrides": {"useUnsupportedUnsafeNonHANonProductionUnstableEtcd": true }}}' --type=merge
    oc patch authentications.operator.openshift.io cluster -p='{"spec": {"unsupportedConfigOverrides": {"useUnsupportedUnsafeNonHANonProductionUnstableOAuthServer": true }}}' --type=merge
  args:
    executable: /bin/bash
  register: single_node_cluster
  changed_when: "single_node_cluster.rc == 0"
  when: (groups['all_control_plane_nodes'] | count) == 1
  delegate_to: "{{ hostvars[kubeinit_deployment_node_name].ansible_host }}"
