---
# Copyright 2020 KubeInit.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.


- name: Delegate to cluster service node hypervisor
  block:

    - name: Prepare podman
      ansible.builtin.include_role:
        name: ../../roles/kubeinit_prepare
        tasks_from: prepare_podman.yml
        public: true

    - name: Setup the services pod
      ansible.builtin.include_role:
        name: ../../roles/kubeinit_services
        tasks_from: 00_create_service_pod.yml
        public: true

    - name: Setup the services container
      ansible.builtin.include_role:
        name: ../../roles/kubeinit_services
        tasks_from: 10_create_provision_container.yml
        public: true

    - name: Prepare credentials for services
      ansible.builtin.include_role:
        name: ../../roles/kubeinit_services
        tasks_from: prepare_credentials.yml
        public: true

    #
    # Configure bind
    #
    - name: Configure Bind
      ansible.builtin.include_role:
        name: ../../roles/kubeinit_bind
        public: true
      when: kubeinit_services_bind_enabled

    #
    # Configure HAproxy
    #
    - name: Configure HAProxy
      ansible.builtin.include_role:
        name: ../../roles/kubeinit_haproxy
        public: true
      when: kubeinit_services_haproxy_enabled

    #
    # Configure Nexus
    #
    - name: Configure Nexus
      ansible.builtin.include_role:
        name: ../../roles/kubeinit_nexus
        public: true
      when: kubeinit_services_nexus_enabled

    #
    # Configure httpd
    #
    - name: Configure Apache
      ansible.builtin.include_role:
        name: ../../roles/kubeinit_apache
        public: true
      when: kubeinit_services_apache_enabled

    #
    # Configure container registry
    #
    - name: Configure a local container image registry
      ansible.builtin.include_role:
        name: ../../roles/kubeinit_registry
        public: true
      when: kubeinit_services_registry_enabled

  delegate_to: "{{ hostvars[kubeinit_deployment_node_name].target }}"

- name: Configure the cluster service node
  ansible.builtin.include_role:
    name: ../../roles/kubeinit_okd
    tasks_from: 10_configure_service_nodes.yml
    public: true
