---
- name: Create OpenShift Ignition Configs
  shell: |
    /usr/local/bin/openshift-baremetal-install --dir {{ cluster_config_dir }} create ignition-configs
  register: create_ign_files
  changed_when: "create_ign_files.rc == 0"

- name: Copy Ignition Config Files
  copy:
    src: "{{ cluster_config_dir }}/{{ item }}.ign"
    dest: "{{ cluster_config_dir }}/{{ item }}.ign.orig"
    remote_src: yes
    mode: '0755'
  with_items:
    - "master"
    - "worker"

- block:
  - name: Verify if {{ ignition_customization_path }}/master/worker is empty
    find:
      paths: "{{ ignition_customization_path }}/{{ item }}"
      recurse: yes
      follow: yes
    register: filesFound
    with_items:
      - "master"
      - "worker"
    delegate_to: localhost

  - name: Create tmp directory to store OpenShift binaries
    tempfile:
      state: directory
    register: tempdiroutput

  - name: Set fact for tmp directory
    set_fact:
      tempdir: "{{ tempdiroutput.path }}"

  - name: Copy customize_ignition to tempdir
    copy:
      src: "{{ ignition_customization_path }}"
      dest: "{{ tempdir }}"
      force: yes
      mode: '0755'

  - name: Cleanup Any .gitkeep Files in the Fake Root
    file:
      path: "{{ ignition_customization_path }}/.gitkeep"
      state: absent
      follow: yes
    with_items:
      - "master"
      - "worker"
    become: true

  - name: Augment Ignition Config Files
    script: |
      filetranspile-1.1.1.py -i {{ cluster_config_dir }}/{{ item }}.ign.orig -f {{ tempdir }}/customize_ignition/{{ item }} -o {{ cluster_config_dir }}/{{ item }}.ign
    register: augment
    changed_when: "augment.rc == 0"
    args:
      executable: python3
    with_items:
      - "master"
      - "worker"
    become: true
  when: ignition_customization_path is defined and ignition_customization_path.stat.exists

- name: Create backup of ignition config files
  copy:
    src: "{{ cluster_config_dir }}/{{ item }}.ign"
    dest: "{{ cluster_config_dir }}/{{ item }}.ign.bkup"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
    remote_src: yes
  with_items:
    - "master"
    - "worker"
