---
- name: Download RHCOS live image
  command: "podman pull {{ coreos_livecd_image }}"
  register: download_rhos
  changed_when: "download_rhos.rc == 0"
  delegate_to: "{{ groups['registry_host'][0] }}"
