---
# Copyright kubeinit contributors
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.


- name: Configure the service node
  block:

    - name: Install common requirements
      ansible.builtin.yum:
        name: "{{ kubeinit_eks_common_dependencies }}"
        state: present
        use_backend: dnf

    #
    # Kubernetes config
    #

    - name: Install requirements for kubectl
      ansible.builtin.package:
        name:
          - "kubectl-{{ kubeinit_eks_kubernetes_version }}"
        state: present

    - name: Install services requirements
      ansible.builtin.yum:
        name: "{{ kubeinit_eks_service_dependencies }}"
        state: present
        use_backend: dnf

    #
    # Configure local registry
    #

    - name: Get the required container images
      ansible.builtin.shell: |
        set -o pipefail
        git clone https://github.com/aws/eks-distro.git
        cd eks-distro
        ./development/pull-all.sh
        podman images | grep public.ecr.aws | awk '{ print $1 ":" $2}' > ~/kubeinit_deployment_images.txt
      args:
        executable: /bin/bash
      register: render_images_list
      changed_when: "render_images_list.rc == 0"

    - name: Mirror EKS remote registry to local
      ansible.builtin.shell: |
        set -o pipefail
        set -e
        mkdir -p /etc/containers/
        cat << EOF > /etc/containers/policy.json
        {
            "default": [
                {
                    "type": "insecureAcceptAnything"
                }
            ],
            "transports":
                {
                    "docker-daemon":
                        {
                            "": [{"type":"insecureAcceptAnything"}]
                        }
                }
        }
        EOF
        echo "function skopeo_copy {" > skopeo_copy.bash
        echo "  skopeo copy docker://\$1 docker://{{ kubeinit_registry_uri }}/\$2 --dest-creds {{ kubeinit_registry_user }}:{{ kubeinit_registry_password }}" >> ~/skopeo_copy.bash
        echo "}" >> ~/skopeo_copy.bash
        sed -e 's;^\(public.ecr.aws/\)\(.*/\)\(.*\);skopeo_copy "\1\2\3" "\2\3"\nskopeo_copy "\1\2\3" "\3";' ~/kubeinit_deployment_images.txt >> ~/skopeo_copy.bash
        bash ~/skopeo_copy.bash
      args:
        executable: /bin/bash
      register: mirror_registry
      changed_when: "mirror_registry.rc == 0"
      when: "'registry' in kubeinit_cluster_hostvars.services"

    - name: Make sure the PK has the correct permissions
      ansible.builtin.shell: |
        set -o pipefail
        # Make sure the private key has the correct perms
        chmod 600 ~/.ssh/id_rsa
      args:
        executable: /bin/bash
      register: ssh_correct_perms
      changed_when: "ssh_correct_perms.rc == 0"

  delegate_to: "{{ hostvars[kubeinit_deployment_node_name].ansible_host }}"
