---
# Copyright kubeinit contributors
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

- name: Deploy the cluster nodes
  ansible.builtin.include_role:
    name: "../../roles/kubeinit_libvirt"
    tasks_from: deploy_centos_guest.yml
    public: yes
  with_items:
    - "{{ groups['all_cluster_nodes'] | list }}"
  loop_control:
    loop_var: cluster_role_item
  vars:
    kubeinit_deployment_node_name: "{{ cluster_role_item }}"
    kubeinit_deployment_role: cluster

- name: Configure the cluster master nodes
  ansible.builtin.include_tasks: 30_configure_controller_nodes.yml
  with_items:
    - "{{ groups['all_controller_nodes'] | list }}"
  loop_control:
    loop_var: cluster_role_item
  vars:
    kubeinit_deployment_node_name: "{{ cluster_role_item }}"
    kubeinit_deployment_role: master

- name: Configure the cluster worker nodes
  ansible.builtin.include_tasks: 40_configure_compute_nodes.yml
  with_items:
    - "{{ groups['all_compute_nodes'] | list }}"
  loop_control:
    loop_var: cluster_role_item
  vars:
    kubeinit_deployment_node_name: "{{ cluster_role_item }}"
    kubeinit_deployment_role: worker

- name: Finish the k8s post deployment tasks
  ansible.builtin.include_tasks: 50_post_deployment_tasks.yml
  with_items:
    - "{{ groups['all_service_nodes'] | list }}"
  loop_control:
    loop_var: cluster_role_item
  vars:
    kubeinit_deployment_node_name: "{{ cluster_role_item }}"
    kubeinit_deployment_role: service

- name: Deploy EKS images
  ansible.builtin.include_tasks: 60_deploy_eks_images.yml
  with_items:
    - "{{ groups['all_service_nodes'] | list }}"
  loop_control:
    loop_var: cluster_role_item
  vars:
    kubeinit_deployment_node_name: "{{ cluster_role_item }}"
    kubeinit_deployment_role: service
