---

- name: Enable Ubuntu repositories
  ansible.builtin.shell: |
    set -o pipefail
    apt-get install software-properties-common -y
    . /etc/os-release
    sudo apt-get update -qq
  args:
    executable: /bin/bash
  register: enable_repos
  changed_when: "enable_repos.rc == 0"
  when: kubeinit_inventory_cluster_distro == 'rke' or kubeinit_inventory_cluster_distro == 'cdk'

- name: Enable CentOS repositories
  ansible.builtin.shell: |
    set -o pipefail
    dnf install -y @container-tools
  args:
    executable: /bin/bash
  register: enable_repos
  changed_when: "enable_repos.rc == 0"
  when: kubeinit_inventory_cluster_distro == 'k8s' or kubeinit_inventory_cluster_distro == 'okd' or kubeinit_inventory_cluster_distro == 'eks'

- name: Make sure needed packages are installed
  ansible.builtin.package:
    state: present
    name: "{{ kubeinit_registry_required_packages | default([]) }}"

- name: Install passlib
  ansible.builtin.shell: |
    set -o pipefail
    python3 -m pip install passlib
  args:
    executable: /bin/bash

- name: Install podman
  ansible.builtin.package:
    state: present
    name: "podman"

- name: Podman login to docker.io
  ansible.builtin.shell: |
    podman login docker.io \
      --username {{ kubeinit_common_docker_username }} --password-stdin
  args:
    executable: /bin/bash
    stdin: "{{ kubeinit_common_docker_password }}"
  register: podman_login
  changed_when: "podman_login.rc == 0"
  when: |
    kubeinit_common_docker_username is defined and
    kubeinit_common_docker_password is defined and
    kubeinit_common_docker_username and
    kubeinit_common_docker_password

- name: Create directory to hold the registry files
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: u=rwX,g=rX,o=rX
    recurse: yes
  with_items:
    - "{{ kubeinit_registry_directory_auth }}"
    - "{{ kubeinit_registry_directory_cert }}"
    - "{{ kubeinit_registry_directory_data }}"
