---

- name: Enable Ubuntu repositories
  ansible.builtin.shell: |
    set -o pipefail
    apt-get install software-properties-common -y
    . /etc/os-release
    sudo apt-get update -qq
  args:
    executable: /bin/bash
  register: enable_repos
  changed_when: "enable_repos.rc == 0"
  when: kubeinit_inventory_cluster_distro == 'rke' or kubeinit_inventory_cluster_distro == 'cdk'

- name: Enable CentOS repositories
  ansible.builtin.shell: |
    set -o pipefail
    dnf install -y @container-tools
  args:
    executable: /bin/bash
  register: enable_repos
  changed_when: "enable_repos.rc == 0"
  when: kubeinit_inventory_cluster_distro == 'k8s' or kubeinit_inventory_cluster_distro == 'okd' or kubeinit_inventory_cluster_distro == 'eks'

- name: Make sure needed packages are installed
  ansible.builtin.package:
    state: present
    name: "{{ kubeinit_registry_required_packages | default([]) }}"

- name: Install passlib
  ansible.builtin.shell: |
    set -o pipefail
    python3 -m pip install passlib
  register: install_passlib
  changed_when: "install_passlib.rc == 0"
  args:
    executable: /bin/bash

- name: Create directory to hold the registry files
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ kubeinit_service_user }}"
    group: "{{ kubeinit_service_user }}"
    mode: u=rwX,g=rX,o=rX
    recurse: yes
  with_items:
    - "{{ kubeinit_registry_directory_auth }}"
    - "{{ kubeinit_registry_directory_cert }}"
    - "{{ kubeinit_registry_directory_data }}"
