- name: Copying token to worker nodes
  copy: src=/home/centos/{{ token_file }} dest=/home/centos/join_token
  tags:
    - worker

- name: Joining worker nodes with kubernetes master
  shell: |
   kubeadm reset -f
   cat /home/centos/join_token | tail -2 > out.sh
   sh out.sh
  tags:
    - worker
