---
- name: Disabling Swap on all nodes
  command: swapoff -a
  changed_when: false
  tags:
    - kubernetes_common

- name: Commenting Swap entries in /etc/fstab
  replace:
    path: /etc/fstab
    regexp: '(.*swap*)'
    replace: '#\1'
  tags:
    - kubernetes_common
