---
- name: Disabling Swap on all nodes
  shell: swapoff -a
  tags:
    - common

- name: Commenting Swap entries in /etc/fstab
  replace:
   path: /etc/fstab
   regexp: '(.*swap*)'
   replace: '#\1'
  tags:
    - common
