---
- name: Installer preparation tasks
  block:
    - include_tasks: 10_get_oc.yml
      tags: installer_preparation_get_oc
    - include_tasks: 20_create_disconnected_registry.yml
      tags: installer_preparation_create_disconnected_registry
    - include_tasks: 30_extract_installer.yml
      tags: installer_preparation_extract_installer
    - include_tasks: 50_get_livecd.yml
      tags: installer_preparation_get_livecd
  tags: installer_preparation
