---
name: docs_build_pr
on:
  pull_request:
    branches:
      - master
    paths:
      - 'docs/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: kubeinit/sphinx-action@master
        with:
          pre-build-command: "touch /tmp/sphinx-log && pip3 install --upgrade pip && pip3 install --upgrade virtualenv && pip3 install --upgrade setuptools && pip3 install --upgrade ansible && pip3 install --upgrade ruamel.yaml && pip3 install --upgrade sphinx-rtd-theme"
          docs-folder: "docs/src/"
      - uses: actions/upload-artifact@v1
        with:
          name: DocumentationHTML
          path: docs/src/_build/html/
